/**
 * 数据表结构定义
 *
 * 表分三类：
 *   1. 已有表（books / words）—— 由 danci-admin 维护，本项目**只读**。
 *      这里仅做 Drizzle 映射，不参与迁移。
 *   2. 新增表（users / user_book_progress / user_word_records）—— 本项目拥有。
 *   3. 视图/聚合 —— 暂不需要。
 *
 * 约定（对齐 danci-admin/db/schema.ts）：
 *   - 表名/列名沿用数据库里的 camelCase，SQL 中必须带双引号。
 *     一律通过 Drizzle 访问，不要手写裸 SQL 字符串。
 *   - dml 脚本生成迁移，勿手改 db/migrations 下的产物。
 *
 * ⚠️ 版本注意：本项目当前安装的是 drizzle-orm@0.29.x，与 danci-admin 的 0.45.x 不同。
 *    0.29 的差异（写本文件时已按 0.29 校对）：
 *      - bigint(name, { mode }) 的 mode 是**必填**，不能省略
 *      - pgTable 的 extraConfig 回调返回**对象**（Record），不是数组
 *    若日后升级到 0.45+，本文件无需大改，但建议复核 bigint/extraConfig 两处。
 */
import { sql } from "drizzle-orm";
import {
  bigint,
  bigserial,
  check,
  index,
  integer,
  json,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/* ========================================================================== *
 * 1. 已有表（只读映射，不参与迁移）
 * ========================================================================== */

/**
 * 单词表
 *
 * 实际 DDL：
 *   id        bigint generated by default as identity not null  -- 主键
 *   wordRank  bigint null      -- 单词在书内排名，从 1 开始
 *   headWord  text null        -- 单词本体，如 "science"
 *   content   json null        -- 词典详情（JSON 对象，非 jsonb！）
 *   bookId    text null        -- 所属单词书业务 ID
 *
 * 关键约束：
 *   - content 是 `json` 而非 `jsonb`，**无法建 GIN 索引**，
 *     所以只能按主键 / bookId 等值查询，不能按 content 内容检索。
 *   - id 是 bigint identity。这里用 mode:'number' 映射为 JS number：
 *     bigserial 主键实际值远小于 Number.MAX_SAFE_INTEGER（9e15），
 *     且 number 能被 JSON.stringify 正常序列化（BigInt 不能）。
 */
export const words = pgTable("words", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  wordRank: bigint("wordRank", { mode: "number" }),
  headWord: text("headWord"),
  content: json("content"),
  bookId: text("bookId"),
});

/**
 * 单词书表
 *
 * 实际 DDL：
 *   id         text not null primary key          -- 形如 "book-m0abc-xyz123"
 *   title      text null
 *   wordCount  integer null default 0             -- 冗余词数，UI 直接读
 *   coverUrl   text null
 *   bookId     text not null unique               -- 业务唯一键，如 "PEPXiaoXue6_1"
 *   tags       text null                          -- JSON 数组字符串 '["初中","PEP"]'
 *   createdAt  timestamptz not null default now()  -- 列表排序键
 *   updatedAt  timestamptz not null default now()  -- 仅审计
 *
 * 注意：books.bookId ⇋ words.bookId 是**弱关联，无外键**。
 * 这是 danci-admin 的既有决策 —— 加 CASCADE 会导致"删一本书连带删掉几万条单词"。
 * 本项目沿用，不要给 words.bookId 加指向 books 的外键。
 */
export const books = pgTable(
  "books",
  {
    id: text("id").primaryKey(),
    title: text("title"),
    wordCount: integer("wordCount").default(0),
    coverUrl: text("coverUrl"),
    bookId: text("bookId").notNull().unique(),
    tags: text("tags"),
    createdAt: timestamp("createdAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updatedAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    bookIdIdx: index("books_book_id_idx").on(table.bookId),
  }),
);

/* ========================================================================== *
 * 2. 新增表（本项目拥有）
 * ========================================================================== */

/**
 * C 端用户表
 *
 * 为什么不复用旧的 "User" 表：
 *   - 表名 "User" 在 PG 里会被小写成 user，语义混淆
 *   - 旧表 email **没有 unique 约束**，并发注册会产生重复账号
 *   - 旧表 password 是 VARCHAR(64)，bcrypt hash 恰好 60 字符，零余量
 *   - 旧表没有 createdAt / updatedAt 审计字段
 *
 * 迁移策略见 db/migrations/0003_migrate_legacy_user.sql：
 * 新建本表 + 幂等搬迁 + 人工校验后才 DROP 旧表。
 */
export const users = pgTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  /** bcrypt hash（60 字符）。用 text 而非 varchar，给算法升级留余量。 */
  passwordHash: text("passwordHash").notNull(),
  /** 可选昵称；为空时上层兜底取 email 的 @ 前缀。 */
  displayName: text("displayName"),
  createdAt: timestamp("createdAt", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updatedAt", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * 用户 × 单词书 的学习进度
 *
 * 支撑两个功能：
 *   - 首页「最近学习」：按 lastStudiedAt 倒序取第一条
 *   - 我的页「学习进度」：列出该用户所有进度
 *
 * 设计要点：
 *   1. bookId **不加外键**（与 danci-admin 一致）。加了 CASCADE 会在后台删书时
 *      连带清空用户学习记录；不加 CASCADE 又可能因历史数据导致删书失败。
 *      保持弱关联，删书后进度行成为孤儿，前端用 LEFT JOIN 查到 null 就不展示。
 *   2. lastWordRank 冗余：学习页需要"从上次单词的**下一个**开始"，
 *      有 rank 就能直接 WHERE wordRank > ?，不必把整本书载入内存再线性查找。
 *   3. lastWordId 可空：用户点进学习页又退出时不必写脏进度。
 */
export const userBookProgress = pgTable(
  "user_book_progress",
  {
    id: text("id").primaryKey(),
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    bookId: text("bookId").notNull(), // 弱关联 books.bookId，不加 FK
    /** 最近学习的单词 words.id */
    lastWordId: bigint("lastWordId", { mode: "number" }),
    /** 冗余该单词在书内的排名，省一次 join */
    lastWordRank: integer("lastWordRank"),
    /** 「最近学习」的排序键 */
    lastStudiedAt: timestamp("lastStudiedAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** 已学单词数（v1 由 user_word_records 聚合，v2 可直接累加） */
    learnedCount: integer("learnedCount").notNull().default(0),
    createdAt: timestamp("createdAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updatedAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    /** 同一用户同一本书只允许一条进度 —— upsert 的冲突目标 */
    userBookUniq: uniqueIndex("user_book_progress_user_book_uniq").on(
      table.userId,
      table.bookId,
    ),
    /** 支撑「最近学习」：WHERE userId = ? ORDER BY lastStudiedAt DESC LIMIT 1 */
    userRecentIdx: index("user_book_progress_user_recent_idx").on(
      table.userId,
      table.lastStudiedAt,
    ),
  }),
);

/**
 * 用户 × 单词 的学习明细
 *
 * v1 需求只要求"记住学到哪"，本表不是必需的；但它是以下能力的**唯一数据来源**：
 *   - 我的页「已学 X / Y」进度百分比
 *   - v2 的间隔重复算法（SRS）需要的复习历史
 * 现在建表的成本远低于以后补建 —— 历史数据无法回溯。
 *
 * status 语义（v1 全部写 'learning'，为 SRS 预留）：
 *   learning — 学习中/刚接触
 *   known    — 已掌握（v2 由 SRS 或用户标记写入）
 *   unknown  — 不认识（v2 预留）
 *
 * bookId 冗余：统计"某本书已学多少"时一次索引扫描即可，无需 join words。
 */
export const userWordRecords = pgTable(
  "user_word_records",
  {
    id: text("id").primaryKey(),
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** words.id，同样是弱关联，不加 FK */
    wordId: bigint("wordId", { mode: "number" }).notNull(),
    bookId: text("bookId").notNull(),
    wordRank: integer("wordRank"),
    status: text("status").notNull().default("learning"),
    studyCount: integer("studyCount").notNull().default(1),
    lastStudiedAt: timestamp("lastStudiedAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("createdAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updatedAt", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    /** 同一用户同一单词只一条记录 —— upsert 的冲突目标 */
    userWordUniq: uniqueIndex("user_word_records_user_word_uniq").on(
      table.userId,
      table.wordId,
    ),
    /** 支撑按书统计：WHERE userId = ? AND bookId = ? GROUP BY status */
    userBookStatusIdx: index("user_word_records_user_book_status_idx").on(
      table.userId,
      table.bookId,
      table.status,
    ),
    /** 约束 status 取值范围，避免脏数据进入 SRS 统计 */
    statusCheck: check(
      "user_word_records_status_check",
      sql`${table.status} in ('learning','known','unknown')`,
    ),
  }),
);

/* ========================================================================== *
 * 3. 类型导出（单一来源，上层统一从这取）
 * ========================================================================== */

// 已有表
export type BookRow = typeof books.$inferSelect;
export type BookInsert = typeof books.$inferInsert;
export type WordRow = typeof words.$inferSelect;
export type WordInsert = typeof words.$inferInsert;

// 新增表
export type UserRow = typeof users.$inferSelect;
export type UserInsert = typeof users.$inferInsert;
export type UserBookProgressRow = typeof userBookProgress.$inferSelect;
export type UserBookProgressInsert = typeof userBookProgress.$inferInsert;
export type UserWordRecordRow = typeof userWordRecords.$inferSelect;
export type UserWordRecordInsert = typeof userWordRecords.$inferInsert;

/** 学习状态枚举（与 user_word_records.status 的 check 约束保持一致） */
export const WORD_STATUSES = ["learning", "known", "unknown"] as const;
export type WordStatus = (typeof WORD_STATUSES)[number];

// 让 sql 保持导入（仓储层手写 SQL 时会用）
export { sql };
