/**
 * 数据表结构定义（按 README 第 71-74 行约定）
 *
 * 在这里用 `pgTable` 定义数据表。
 */
import { sql } from "drizzle-orm";
import {
  bigserial,
  integer,
  json,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

/**
 * 管理员角色枚举
 * - super：系统管理员（首个注册者永远是 super，可管理其他管理员）
 * - normal：普通管理员（只能使用单词书等业务功能）
 */
export const adminRoleEnum = pgEnum("admin_role", ["super", "normal"]);

/**
 * 管理员账号状态枚举
 * - active  ：正常启用，可登录后台
 * - disabled：停用，禁止登录（保留账号与历史数据）
 */
export const adminStatusEnum = pgEnum("admin_status", [
  "active",
  "disabled",
]);

/**
 * 管理员账户表
 */
export const adminUsers = pgTable("admin_users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  role: adminRoleEnum("role").notNull().default("normal"),
  status: adminStatusEnum("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * 管理员登录会话表
 * - sessionId：写入 HttpOnly cookie 的值（随机字符串）
 * - adminId：所属管理员
 * - expiresAt：7 天后过期；服务端读 cookie 时回查并校验过期
 */
export const adminSession = pgTable("admin_session", {
  id: text("id").primaryKey(),
  adminId: text("admin_id")
    .notNull()
    .references(() => adminUsers.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
});

/**
 * 单词表
 *
 * 数据来源：从 `temp/<bookId>.json`（金山词霸 / 有道词典导出格式）经
 * `scripts/json2csv.mjs` 转 CSV 后批量导入。每本书一本大表，共用一个 schema。
 *
 * 字段说明：
 * - id            ：自增主键（bigserial，对应 Postgres `bigint generated by default as identity`）
 * - wordRank      ：单词在所属单词书里的排名（1, 2, 3, ...）
 * - headWord      ：单词本身（"abandon" / "a" 这种）
 * - content       ：原始词典详情（JSON 对象）。导入时把每行的 `content` 字段
 *                   `JSON.stringify` 后塞进这里，读取时再 `JSON.parse` 还原。
 *                   用 `json` 类型（不是 `jsonb`）以匹配 Supabase 表里既有的定义。
 * - bookId        ：所属单词书的标识（如 "CET4_2"、"PEPXiaoXue6_1"），用于按书筛选
 */
export const words = pgTable("words", {
  id: bigserial("id", { mode: "bigint" }).primaryKey(),
  wordRank: integer("wordRank"),
  headWord: text("headWord"),
  content: json("content"),
  bookId: text("bookId"),
});

// 导出类型，方便上层使用
export type AdminUserRow = typeof adminUsers.$inferSelect;
export type AdminUserInsert = typeof adminUsers.$inferInsert;
export type AdminSessionRow = typeof adminSession.$inferSelect;
export type AdminSessionInsert = typeof adminSession.$inferInsert;
export type WordRow = typeof words.$inferSelect;
export type WordInsert = typeof words.$inferInsert;
export type AdminRole = (typeof adminRoleEnum.enumValues)[number]; // "super" | "normal"
export type AdminStatus = (typeof adminStatusEnum.enumValues)[number]; // "active" | "disabled"

// 业务上需要的视图类型：不含 passwordHash
export type SafeAdmin = {
  id: string;
  name: string;
  email: string;
  role: AdminRole;
  status: AdminStatus;
  createdAt: Date | string;
};

// 让 `sql` 保持导入（drizzle-orm 工具函数，后续可能用到）
export { sql };
